name: database
version: 0.3.4
description:
  A database access API that's vendor-agnostic. Adapters exist for browser APIs, SQLite, Google
  Cloud Firestore, PostgreSQL, ElasticSearch, Algolia, and others.
homepage: https://github.com/dint-dev/database

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.4.0
  charcode: ^1.3.1
  collection: ^1.16.0
  fixnum: ^1.0.1
  meta: ^1.7.0
  protobuf: ^2.1.0
  universal_html: ^2.0.8
  universal_io: ^2.0.4

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.8.0